const fpi = {
  nameAllofactor1: {
    keterangan: "Name 1",
    satuan: "Unit",
    type: "text",
    disabled: false,
    placeholder: "Input Name",
  },
  nameAllofactor2: {
    keterangan: "Name 2",
    satuan: "Unit",
    type: "text",
    disabled: false,
    placeholder: "Input Name",
  },
  nameAllofactor3: {
    keterangan: "Name 3",
    satuan: "Unit",
    type: "text",
    disabled: false,
    placeholder: "Input Name",
  },
  nameAllofactor4: {
    keterangan: "Name 4",
    satuan: "Unit",
    type: "text",
    disabled: false,
    placeholder: "Input Name",
  },
  nameAllofactor5: {
    keterangan: "Name 5",
    satuan: "Unit",
    type: "text",
    disabled: false,
    placeholder: "Input Name",
  },
  nameAllofactor6: {
    keterangan: "Name 6",
    satuan: "Unit",
    type: "text",
    disabled: false,
    placeholder: "Input Name",
  },
  nameAllofactor7: {
    keterangan: "Name 7",
    satuan: "Unit",
    type: "text",
    disabled: false,
    placeholder: "Input Name",
  },
  nameAllofactor8: {
    keterangan: "Name 8",
    satuan: "Unit",
    type: "text",
    disabled: false,
    placeholder: "Input Name",
  },
  nameAllofactor9: {
    keterangan: "Name 9",
    satuan: "Unit",
    type: "text",
    disabled: false,
    placeholder: "Input Name",
  },
  nameAllofactor10: {
    keterangan: "Name 10",
    satuan: "Unit",
    type: "text",
    disabled: false,
    placeholder: "Input Name",
  },
  nameAllofactor11: {
    keterangan: "Name 11",
    satuan: "Unit",
    type: "text",
    disabled: false,
    placeholder: "Input Name",
  },
};

export default fpi;
