const allocation = {
  nameAllofaction: {
    keterangan: "Name",
    satuan: "Unit",
    type: "text",
    disabled: false,
    placeholder: "Input Name",
    labelColor: "text-black",
    bold: true,
  },
  nameAllofactor1: {
    keterangan: "",
    satuan: "",
    type: "text",
    disabled: false,
    placeholder: "Input Name",
    labelColor: "text-black",
    bold: false,
  },
  nameAllofactor2: {
    keterangan: "",
    satuan: "",
    type: "text",
    disabled: false,
    placeholder: "Input Name",
    labelColor: "text-black",
    bold: false,
  },
  nameAllofactor3: {
    keterangan: "",
    satuan: "",
    type: "text",
    disabled: false,
    placeholder: "Input Name",
    labelColor: "text-black",
    bold: false,
  },
  nameAllofactor4: {
    keterangan: "",
    satuan: "",
    type: "text",
    disabled: false,
    placeholder: "Input Name",
    labelColor: "text-black",
    bold: false,
  },
  nameAllofactor5: {
    keterangan: "",
    satuan: "",
    type: "text",
    disabled: false,
    placeholder: "Input Name",
    labelColor: "text-black",
    bold: false,
  },
  nameAllofactor6: {
    keterangan: "",
    satuan: "",
    type: "text",
    disabled: false,
    placeholder: "Input Name",
    labelColor: "text-black",
    bold: false,
  },
  nameAllofactor7: {
    keterangan: "",
    satuan: "",
    type: "text",
    disabled: false,
    placeholder: "Input Name",
    labelColor: "text-black",
    bold: false,
  },
  nameAllofactor8: {
    keterangan: "",
    satuan: "",
    type: "text",
    disabled: false,
    placeholder: "Input Name",
    labelColor: "text-black",
    bold: false,
  },
  nameAllofactor9: {
    keterangan: "",
    satuan: "",
    type: "text",
    disabled: false,
    placeholder: "Input Name",
    labelColor: "text-black",
    bold: false,
  },
  nameAllofactor10: {
    keterangan: "",
    satuan: "",
    type: "text",
    disabled: false,
    placeholder: "Input Name",
    labelColor: "text-black",
    bold: false,
  },
  nameAllofactor11: {
    keterangan: "",
    satuan: "",
    type: "text",
    disabled: false,
    placeholder: "Input Name",
    labelColor: "text-black",
    bold: false,
  },
};

export default allocation;
