CREATE TABLE "step_dua_ghg_calculation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "step_dua_ghg_calculation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"carbon_project_id" uuid NOT NULL,
	"keterangan" text NOT NULL,
	"nilai_int" integer,
	"nilai_string" text,
	"satuan" text,
	"source" text
);
--> statement-breakpoint
CREATE TABLE "step_empat_ghg_audit" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "step_empat_ghg_audit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"carbon_project_id" uuid NOT NULL,
	"keterangan" text NOT NULL,
	"nilai_int" integer,
	"nilai_string" text,
	"satuan" text,
	"source" text
);
--> statement-breakpoint
CREATE TABLE "step_satu_ghg_verification" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "step_satu_ghg_verification_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"carbon_project_id" uuid NOT NULL,
	"keterangan" text NOT NULL,
	"nilai_int" integer,
	"nilai_string" text,
	"satuan" text,
	"source" text
);
--> statement-breakpoint
CREATE TABLE "step_tiga_additional" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "step_tiga_additional_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"carbon_project_id" uuid NOT NULL,
	"keterangan" text NOT NULL,
	"nilai_int" integer,
	"nilai_string" text,
	"satuan" text,
	"source" text
);
--> statement-breakpoint
CREATE TABLE "step_tiga_ghg_calculation_process" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "step_tiga_ghg_calculation_process_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"carbon_project_id" uuid NOT NULL,
	"keterangan" text NOT NULL,
	"nilai_int" integer,
	"nilai_string" text,
	"satuan" text,
	"source" text
);
--> statement-breakpoint
CREATE TABLE "step_tiga_other_case" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "step_tiga_other_case_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"carbon_project_id" uuid NOT NULL,
	"keterangan" text NOT NULL,
	"nilai_int" integer,
	"nilai_string" text,
	"satuan" text,
	"source" text
);
--> statement-breakpoint
DROP TABLE "actual_carbon" CASCADE;--> statement-breakpoint
DROP TABLE "cultivation" CASCADE;--> statement-breakpoint
DROP TABLE "energy_diesel" CASCADE;--> statement-breakpoint
DROP TABLE "energy_electricity" CASCADE;--> statement-breakpoint
DROP TABLE "fertilizer_nitrogen" CASCADE;--> statement-breakpoint
DROP TABLE "herbicides" CASCADE;--> statement-breakpoint
DROP TABLE "products" CASCADE;--> statement-breakpoint
DROP TABLE "raws" CASCADE;--> statement-breakpoint
DROP TABLE "reference_carbon" CASCADE;--> statement-breakpoint
ALTER TABLE "step_dua_ghg_calculation" ADD CONSTRAINT "step_dua_ghg_calculation_carbon_project_id_carbon_project_id_fk" FOREIGN KEY ("carbon_project_id") REFERENCES "public"."carbon_project"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "step_empat_ghg_audit" ADD CONSTRAINT "step_empat_ghg_audit_carbon_project_id_carbon_project_id_fk" FOREIGN KEY ("carbon_project_id") REFERENCES "public"."carbon_project"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "step_satu_ghg_verification" ADD CONSTRAINT "step_satu_ghg_verification_carbon_project_id_carbon_project_id_fk" FOREIGN KEY ("carbon_project_id") REFERENCES "public"."carbon_project"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "step_tiga_additional" ADD CONSTRAINT "step_tiga_additional_carbon_project_id_carbon_project_id_fk" FOREIGN KEY ("carbon_project_id") REFERENCES "public"."carbon_project"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "step_tiga_ghg_calculation_process" ADD CONSTRAINT "step_tiga_ghg_calculation_process_carbon_project_id_carbon_project_id_fk" FOREIGN KEY ("carbon_project_id") REFERENCES "public"."carbon_project"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "step_tiga_other_case" ADD CONSTRAINT "step_tiga_other_case_carbon_project_id_carbon_project_id_fk" FOREIGN KEY ("carbon_project_id") REFERENCES "public"."carbon_project"("id") ON DELETE cascade ON UPDATE no action;