export const IPCC_EMISSION_FACTORS = [
  {
    name: "Natural Gas Combustion - Residential",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "1.930000",
    unit: "kg_CO2/m3",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 2",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Paper/Cardboard - Landfill",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "0.350000",
    unit: "ton_CH4/ton_waste",
    source: "IPCC 2006 Guidelines, Volume 5, Chapter 3, Country-specific DOC",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Paper/Cardboard - Landfill",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "0.350000",
    unit: "ton_CH4/ton_waste",
    source: "IPCC 2006 Guidelines, Volume 5, Chapter 3, Country-specific DOC",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Diesel Combustion CH4 - Road Transport",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "0.003200",
    unit: "kg_CH4/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Technology-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Dairy Cattle Manure - CH4",
    gas_type: "CH4",
    tier: "TIER_3",
    value: "25.000000",
    unit: "kg_CH4/head/year",
    source:
      "IPCC 2006 Guidelines, Volume 4, Chapter 10, Detailed characterization",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Swine Manure - N2O",
    gas_type: "N2O",
    tier: "TIER_2",
    value: "0.140000",
    unit: "kg_N2O/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Management-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Municipal Solid Waste - Landfill",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "0.600000",
    unit: "ton_CH4/ton_waste",
    source: "IPCC 2006 Guidelines, Volume 5, Chapter 3, Table 3.1",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Wastewater Treatment - Domestic",
    gas_type: "N2O",
    tier: "TIER_1",
    value: "0.005000",
    unit: "kg_N2O-N/kg_N",
    source: "IPCC 2006 Guidelines, Volume 5, Chapter 6",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Food Waste - Landfill",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "0.150000",
    unit: "ton_CH4/ton_waste",
    source: "IPCC 2006 Guidelines, Volume 5, Chapter 3, Table 3.1",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Fertilizer Application - N2O Direct",
    gas_type: "N2O",
    tier: "TIER_3",
    value: "0.007200",
    unit: "kg_N2O-N/kg_N",
    source:
      "IPCC 2006 Guidelines, Volume 4, Chapter 11, Process-based simulation",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Non-Dairy Cattle Manure - CH4",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "1.000000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.14",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "LPG Combustion - Residential",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "3.000000",
    unit: "kg_CO2/kg",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 2",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Poultry Manure - CH4",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "0.095000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, System-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Wood Combustion N2O - Residential",
    gas_type: "N2O",
    tier: "TIER_2",
    value: "0.003500",
    unit: "kg_N2O/ton",
    source:
      "IPCC 2006 Guidelines, Volume 2, Chapter 2, Combustion efficiency-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Ammonia Production",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "1.650000",
    unit: "ton_CO2/ton_NH3",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 3",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Swine Manure - CH4",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "7.000000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.14",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Dairy Cattle - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "68.000000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.10",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Coal Combustion - Power Generation",
    gas_type: "CO2",
    tier: "TIER_3",
    value: "2.510000",
    unit: "kg_CO2/kg",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 2, CEMS",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Wood Combustion - Residential",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "0.280000",
    unit: "kg_CH4/ton",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 2, Appliance-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Wastewater Treatment - Domestic",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "0.600000",
    unit: "kg_CH4/kg_BOD",
    source: "IPCC 2006 Guidelines, Volume 5, Chapter 6",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Dairy Cattle Manure - CH4",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "31.000000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.14",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Coal Combustion - Power Generation",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "2.450000",
    unit: "kg_CO2/kg",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 2",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "LPG Combustion - Road Transport",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "1.670000",
    unit: "kg_CO2/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Table 3.3.1",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Cement Production - Process Emissions",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "0.510000",
    unit: "ton_CO2/ton_clinker",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 2, Plant-specific CaO",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Wood Combustion - Residential",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "0.300000",
    unit: "kg_CH4/ton",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 2, Table 2.5",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Non-Dairy Cattle Manure - CH4",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "0.850000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Climate-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Swine Manure - N2O",
    gas_type: "N2O",
    tier: "TIER_1",
    value: "0.160000",
    unit: "kg_N2O/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.21",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Poultry Manure - N2O",
    gas_type: "N2O",
    tier: "TIER_1",
    value: "0.020000",
    unit: "kg_N2O/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.21",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Non-Dairy Cattle - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_3",
    value: "71.000000",
    unit: "kg_CH4/head/year",
    source:
      "IPCC 2006 Guidelines, Volume 4, Chapter 10, Feed digestibility model",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Coal Combustion - Residential",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "2.380000",
    unit: "kg_CO2/kg",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 2, Coal type-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "LPG Combustion - Road Transport",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "1.670000",
    unit: "kg_CO2/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Table 3.3.1",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "SF6 - Electrical Equipment",
    gas_type: "SF6",
    tier: "TIER_3",
    value: "0.035000",
    unit: "kg_SF6/equipment/year",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 8, Inventory tracking",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "HFC-134a Refrigerant Leakage",
    gas_type: "HFCs",
    tier: "TIER_2",
    value: "0.120000",
    unit: "kg_HFC/kg_charge/year",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 7, Equipment-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Dairy Cattle - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "75.000000",
    unit: "kg_CH4/head/year",
    source:
      "IPCC 2006 Guidelines, Volume 4, Chapter 10, Region-specific production",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "SF6 - Electrical Equipment",
    gas_type: "SF6",
    tier: "TIER_1",
    value: "0.050000",
    unit: "kg_SF6/equipment/year",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 8",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Aviation Gasoline Combustion",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "2.280000",
    unit: "kg_CO2/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Table 3.6.3",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Cement Production - Process Emissions",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "0.510000",
    unit: "ton_CO2/ton_clinker",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 2, Plant-specific CaO",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Wastewater Treatment - Domestic",
    gas_type: "N2O",
    tier: "TIER_2",
    value: "0.004200",
    unit: "kg_N2O-N/kg_N",
    source: "IPCC 2006 Guidelines, Volume 5, Chapter 6, Plant-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Coal Combustion - Residential",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "2.380000",
    unit: "kg_CO2/kg",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 2, Coal type-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Coal Combustion - Residential",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "2.420000",
    unit: "kg_CO2/kg",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 2",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Diesel Combustion N2O - Road Transport",
    gas_type: "N2O",
    tier: "TIER_2",
    value: "0.000380",
    unit: "kg_N2O/liter",
    source:
      "IPCC 2006 Guidelines, Volume 2, Chapter 3, Vehicle category-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Food Waste - Landfill",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "0.140000",
    unit: "ton_CH4/ton_waste",
    source: "IPCC 2006 Guidelines, Volume 5, Chapter 3, Climate-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Swine - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "1.200000",
    unit: "kg_CH4/head/year",
    source:
      "IPCC 2006 Guidelines, Volume 4, Chapter 10, Production system-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Rice Cultivation - Methane",
    gas_type: "CH4",
    tier: "TIER_3",
    value: "0.980000",
    unit: "kg_CH4/ha/season",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 5, DNDC model",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Non-Dairy Cattle Manure - CH4",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "0.850000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Climate-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Fertilizer Application - N2O Direct",
    gas_type: "N2O",
    tier: "TIER_3",
    value: "0.007200",
    unit: "kg_N2O-N/kg_N",
    source:
      "IPCC 2006 Guidelines, Volume 4, Chapter 11, Process-based simulation",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "HFC-134a Refrigerant Leakage",
    gas_type: "HFCs",
    tier: "TIER_3",
    value: "0.095000",
    unit: "kg_HFC/kg_charge/year",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 7, Direct monitoring",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Food Waste - Landfill",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "0.150000",
    unit: "ton_CH4/ton_waste",
    source: "IPCC 2006 Guidelines, Volume 5, Chapter 3, Table 3.1",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Ammonia Production",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "1.650000",
    unit: "ton_CO2/ton_NH3",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 3",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Garden/Park Waste - Landfill",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "0.200000",
    unit: "ton_CH4/ton_waste",
    source: "IPCC 2006 Guidelines, Volume 5, Chapter 3, Table 3.1",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Aviation Gasoline Combustion",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "2.280000",
    unit: "kg_CO2/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Table 3.6.3",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Sheep - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "5.000000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.10",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Poultry Manure - N2O",
    gas_type: "N2O",
    tier: "TIER_1",
    value: "0.020000",
    unit: "kg_N2O/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.21",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "HFC-134a Refrigerant Leakage",
    gas_type: "HFCs",
    tier: "TIER_1",
    value: "0.150000",
    unit: "kg_HFC/kg_charge/year",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 7, Table 7.9",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "SF6 - Electrical Equipment",
    gas_type: "SF6",
    tier: "TIER_2",
    value: "0.042000",
    unit: "kg_SF6/equipment/year",
    source:
      "IPCC 2006 Guidelines, Volume 3, Chapter 8, Equipment type-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "HFC-134a Refrigerant Leakage",
    gas_type: "HFCs",
    tier: "TIER_3",
    value: "0.095000",
    unit: "kg_HFC/kg_charge/year",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 7, Direct monitoring",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Coal Combustion - Power Generation",
    gas_type: "CO2",
    tier: "TIER_3",
    value: "2.510000",
    unit: "kg_CO2/kg",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 2, CEMS",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Gasoline Combustion - Road Transport",
    gas_type: "CO2",
    tier: "TIER_3",
    value: "2.290000",
    unit: "kg_CO2/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Direct measurement",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Garden/Park Waste - Landfill",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "0.180000",
    unit: "ton_CH4/ton_waste",
    source: "IPCC 2006 Guidelines, Volume 5, Chapter 3, Moisture-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Jet Kerosene Combustion - Aviation",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "2.520000",
    unit: "kg_CO2/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Table 3.6.3",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Dairy Cattle Manure - N2O",
    gas_type: "N2O",
    tier: "TIER_2",
    value: "0.380000",
    unit: "kg_N2O/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Climate-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "LPG Combustion - Residential",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "2.980000",
    unit: "kg_CO2/kg",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 2, Country-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Swine Manure - CH4",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "6.200000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Temperature-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Dairy Cattle - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "75.000000",
    unit: "kg_CH4/head/year",
    source:
      "IPCC 2006 Guidelines, Volume 4, Chapter 10, Region-specific production",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Wood Combustion N2O - Residential",
    gas_type: "N2O",
    tier: "TIER_1",
    value: "0.004000",
    unit: "kg_N2O/ton",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 2, Table 2.5",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Non-Dairy Cattle - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "63.000000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Weight-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Poultry Manure - CH4",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "0.095000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, System-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Diesel Combustion N2O - Road Transport",
    gas_type: "N2O",
    tier: "TIER_1",
    value: "0.000400",
    unit: "kg_N2O/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Table 3.3.1",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Fertilizer Application - N2O Direct",
    gas_type: "N2O",
    tier: "TIER_1",
    value: "0.010000",
    unit: "kg_N2O-N/kg_N",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 11",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Rice Cultivation - Methane",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "1.300000",
    unit: "kg_CH4/ha/season",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 5",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Paper/Cardboard - Landfill",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "0.400000",
    unit: "ton_CH4/ton_waste",
    source: "IPCC 2006 Guidelines, Volume 5, Chapter 3, Table 3.1",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Diesel Combustion N2O - Road Transport",
    gas_type: "N2O",
    tier: "TIER_2",
    value: "0.000380",
    unit: "kg_N2O/liter",
    source:
      "IPCC 2006 Guidelines, Volume 2, Chapter 3, Vehicle category-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Aviation Gasoline Combustion",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "2.310000",
    unit: "kg_CO2/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Country-specific NCV",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Diesel Combustion - Road Transport",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "2.680000",
    unit: "kg_CO2/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Table 3.3.1",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Steel Production - Blast Furnace",
    gas_type: "CO2",
    tier: "TIER_3",
    value: "1.780000",
    unit: "ton_CO2/ton_steel",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 4, Mass balance approach",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "HFC-134a Refrigerant Leakage",
    gas_type: "HFCs",
    tier: "TIER_2",
    value: "0.120000",
    unit: "kg_HFC/kg_charge/year",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 7, Equipment-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Fertilizer Application - N2O Direct",
    gas_type: "N2O",
    tier: "TIER_2",
    value: "0.008500",
    unit: "kg_N2O-N/kg_N",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 11, Soil-climate specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Buffalo - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "55.000000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.10",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "SF6 - Electrical Equipment",
    gas_type: "SF6",
    tier: "TIER_1",
    value: "0.050000",
    unit: "kg_SF6/equipment/year",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 8",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Diesel Combustion N2O - Road Transport",
    gas_type: "N2O",
    tier: "TIER_1",
    value: "0.000400",
    unit: "kg_N2O/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Table 3.3.1",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "LPG Combustion - Residential",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "3.000000",
    unit: "kg_CO2/kg",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 2",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Sheep - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "6.200000",
    unit: "kg_CH4/head/year",
    source:
      "IPCC 2006 Guidelines, Volume 4, Chapter 10, Production type-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Ammonia Production",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "1.580000",
    unit: "ton_CO2/ton_NH3",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 3, Process-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "SF6 - Electrical Equipment",
    gas_type: "SF6",
    tier: "TIER_3",
    value: "0.035000",
    unit: "kg_SF6/equipment/year",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 8, Inventory tracking",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Ammonia Production",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "1.580000",
    unit: "ton_CO2/ton_NH3",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 3, Process-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Lime Production - Process",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "0.750000",
    unit: "ton_CO2/ton_lime",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 2",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Natural Gas Combustion - Residential",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "1.950000",
    unit: "kg_CO2/m3",
    source:
      "IPCC 2006 Guidelines, Volume 2, Chapter 2, Gas composition-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Steel Production - Blast Furnace",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "1.820000",
    unit: "ton_CO2/ton_steel",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 4, Facility-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Dairy Cattle Manure - CH4",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "28.000000",
    unit: "kg_CH4/head/year",
    source:
      "IPCC 2006 Guidelines, Volume 4, Chapter 10, Management system-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Dairy Cattle Manure - CH4",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "28.000000",
    unit: "kg_CH4/head/year",
    source:
      "IPCC 2006 Guidelines, Volume 4, Chapter 10, Management system-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Diesel Combustion CH4 - Road Transport",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "0.003900",
    unit: "kg_CH4/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Table 3.3.1",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Dairy Cattle Manure - CH4",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "31.000000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.14",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Gasoline Combustion - Road Transport",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "2.330000",
    unit: "kg_CO2/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Fuel quality-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Swine Manure - CH4",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "6.200000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Temperature-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Wastewater Treatment - Domestic",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "0.600000",
    unit: "kg_CH4/kg_BOD",
    source: "IPCC 2006 Guidelines, Volume 5, Chapter 6",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Dairy Cattle Manure - N2O",
    gas_type: "N2O",
    tier: "TIER_3",
    value: "0.320000",
    unit: "kg_N2O/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Process-based model",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Gasoline Combustion - Road Transport",
    gas_type: "CO2",
    tier: "TIER_3",
    value: "2.290000",
    unit: "kg_CO2/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Direct measurement",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Natural Gas Combustion - Residential",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "1.950000",
    unit: "kg_CO2/m3",
    source:
      "IPCC 2006 Guidelines, Volume 2, Chapter 2, Gas composition-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Poultry Manure - CH4",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "0.110000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.14",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Diesel Combustion CH4 - Road Transport",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "0.003900",
    unit: "kg_CH4/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Table 3.3.1",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Wastewater Treatment - Domestic",
    gas_type: "CH4",
    tier: "TIER_3",
    value: "0.450000",
    unit: "kg_CH4/kg_BOD",
    source: "IPCC 2006 Guidelines, Volume 5, Chapter 6, Site measurement",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Coal Combustion - Power Generation",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "2.480000",
    unit: "kg_CO2/kg",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 2, Plant-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Swine Manure - N2O",
    gas_type: "N2O",
    tier: "TIER_1",
    value: "0.160000",
    unit: "kg_N2O/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.21",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Cement Production - Process Emissions",
    gas_type: "CO2",
    tier: "TIER_3",
    value: "0.495000",
    unit: "ton_CO2/ton_clinker",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 2, Continuous monitoring",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Non-Dairy Cattle - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "57.000000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.10",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Lime Production - Process",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "0.750000",
    unit: "ton_CO2/ton_lime",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 2",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Non-Dairy Cattle - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "57.000000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.10",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Goats - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "5.000000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.10",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Wastewater Treatment - Domestic",
    gas_type: "N2O",
    tier: "TIER_1",
    value: "0.005000",
    unit: "kg_N2O-N/kg_N",
    source: "IPCC 2006 Guidelines, Volume 5, Chapter 6",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "LPG Combustion - Residential",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "2.980000",
    unit: "kg_CO2/kg",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 2, Country-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Jet Kerosene Combustion - Aviation",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "2.520000",
    unit: "kg_CO2/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Table 3.6.3",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Wastewater Treatment - Domestic",
    gas_type: "CH4",
    tier: "TIER_3",
    value: "0.450000",
    unit: "kg_CH4/kg_BOD",
    source: "IPCC 2006 Guidelines, Volume 5, Chapter 6, Site measurement",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Non-Dairy Cattle - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_3",
    value: "71.000000",
    unit: "kg_CH4/head/year",
    source:
      "IPCC 2006 Guidelines, Volume 4, Chapter 10, Feed digestibility model",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Swine - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "1.200000",
    unit: "kg_CH4/head/year",
    source:
      "IPCC 2006 Guidelines, Volume 4, Chapter 10, Production system-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Coal Combustion - Residential",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "2.420000",
    unit: "kg_CO2/kg",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 2",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Dairy Cattle Manure - N2O",
    gas_type: "N2O",
    tier: "TIER_1",
    value: "0.440000",
    unit: "kg_N2O/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.21",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Steel Production - Blast Furnace",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "1.820000",
    unit: "ton_CO2/ton_steel",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 4, Facility-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "LPG Combustion - Road Transport",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "1.690000",
    unit: "kg_CO2/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Country-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Food Waste - Landfill",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "0.140000",
    unit: "ton_CH4/ton_waste",
    source: "IPCC 2006 Guidelines, Volume 5, Chapter 3, Climate-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Diesel Combustion - Road Transport",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "2.680000",
    unit: "kg_CO2/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Table 3.3.1",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Wastewater Treatment - Domestic",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "0.520000",
    unit: "kg_CH4/kg_BOD",
    source:
      "IPCC 2006 Guidelines, Volume 5, Chapter 6, Treatment system-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Wood Combustion N2O - Residential",
    gas_type: "N2O",
    tier: "TIER_1",
    value: "0.004000",
    unit: "kg_N2O/ton",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 2, Table 2.5",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Wastewater Treatment - Domestic",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "0.520000",
    unit: "kg_CH4/kg_BOD",
    source:
      "IPCC 2006 Guidelines, Volume 5, Chapter 6, Treatment system-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Dairy Cattle - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_3",
    value: "82.000000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Feed-based model",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Dairy Cattle - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "68.000000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.10",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Gasoline Combustion - Road Transport",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "2.310000",
    unit: "kg_CO2/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Table 3.3.1",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Swine - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "1.000000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.10",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Municipal Solid Waste - Landfill",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "0.550000",
    unit: "ton_CH4/ton_waste",
    source:
      "IPCC 2006 Guidelines, Volume 5, Chapter 3, Waste composition-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Non-Dairy Cattle - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "63.000000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Weight-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Steel Production - Blast Furnace",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "1.850000",
    unit: "ton_CO2/ton_steel",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 4",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Gasoline Combustion - Road Transport",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "2.330000",
    unit: "kg_CO2/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Fuel quality-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Dairy Cattle Manure - N2O",
    gas_type: "N2O",
    tier: "TIER_2",
    value: "0.380000",
    unit: "kg_N2O/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Climate-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Buffalo - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "55.000000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.10",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Gasoline Combustion - Road Transport",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "2.310000",
    unit: "kg_CO2/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Table 3.3.1",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Cement Production - Process Emissions",
    gas_type: "CO2",
    tier: "TIER_3",
    value: "0.495000",
    unit: "ton_CO2/ton_clinker",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 2, Continuous monitoring",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Jet Kerosene Combustion - Aviation",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "2.540000",
    unit: "kg_CO2/liter",
    source:
      "IPCC 2006 Guidelines, Volume 2, Chapter 3, Fuel specification-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Rice Cultivation - Methane",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "1.150000",
    unit: "kg_CH4/ha/season",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 5, Water regime-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Wood Combustion N2O - Residential",
    gas_type: "N2O",
    tier: "TIER_2",
    value: "0.003500",
    unit: "kg_N2O/ton",
    source:
      "IPCC 2006 Guidelines, Volume 2, Chapter 2, Combustion efficiency-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Buffalo - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "62.000000",
    unit: "kg_CH4/head/year",
    source:
      "IPCC 2006 Guidelines, Volume 4, Chapter 10, Regional characteristics",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Sheep - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "5.000000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.10",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Lime Production - Process",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "0.730000",
    unit: "ton_CO2/ton_lime",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 2, Lime type-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Cement Production - Process Emissions",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "0.520000",
    unit: "ton_CO2/ton_clinker",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 2, Equation 2.1",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Rice Cultivation - Methane",
    gas_type: "CH4",
    tier: "TIER_3",
    value: "0.980000",
    unit: "kg_CH4/ha/season",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 5, DNDC model",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "HFC-134a Refrigerant Leakage",
    gas_type: "HFCs",
    tier: "TIER_1",
    value: "0.150000",
    unit: "kg_HFC/kg_charge/year",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 7, Table 7.9",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Poultry Manure - N2O",
    gas_type: "N2O",
    tier: "TIER_2",
    value: "0.018000",
    unit: "kg_N2O/head/year",
    source:
      "IPCC 2006 Guidelines, Volume 4, Chapter 10, Housing system-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Goats - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "4.200000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Country-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Wood Combustion - Residential",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "0.300000",
    unit: "kg_CH4/ton",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 2, Table 2.5",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Swine Manure - N2O",
    gas_type: "N2O",
    tier: "TIER_2",
    value: "0.140000",
    unit: "kg_N2O/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Management-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Goats - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "4.200000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Country-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Lime Production - Process",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "0.730000",
    unit: "ton_CO2/ton_lime",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 2, Lime type-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Wastewater Treatment - Domestic",
    gas_type: "N2O",
    tier: "TIER_2",
    value: "0.004200",
    unit: "kg_N2O-N/kg_N",
    source: "IPCC 2006 Guidelines, Volume 5, Chapter 6, Plant-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Rice Cultivation - Methane",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "1.300000",
    unit: "kg_CH4/ha/season",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 5",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Diesel Combustion - Road Transport",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "2.710000",
    unit: "kg_CO2/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Country-specific NCV",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Fertilizer Application - N2O Direct",
    gas_type: "N2O",
    tier: "TIER_2",
    value: "0.008500",
    unit: "kg_N2O-N/kg_N",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 11, Soil-climate specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Poultry Manure - N2O",
    gas_type: "N2O",
    tier: "TIER_2",
    value: "0.018000",
    unit: "kg_N2O/head/year",
    source:
      "IPCC 2006 Guidelines, Volume 4, Chapter 10, Housing system-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Municipal Solid Waste - Landfill",
    gas_type: "CH4",
    tier: "TIER_3",
    value: "0.480000",
    unit: "ton_CH4/ton_waste",
    source: "IPCC 2006 Guidelines, Volume 5, Chapter 3, FOD model",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Non-Dairy Cattle Manure - CH4",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "1.000000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.14",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Coal Combustion - Power Generation",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "2.480000",
    unit: "kg_CO2/kg",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 2, Plant-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Dairy Cattle Manure - CH4",
    gas_type: "CH4",
    tier: "TIER_3",
    value: "25.000000",
    unit: "kg_CH4/head/year",
    source:
      "IPCC 2006 Guidelines, Volume 4, Chapter 10, Detailed characterization",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Swine - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "1.000000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.10",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Fertilizer Application - N2O Direct",
    gas_type: "N2O",
    tier: "TIER_1",
    value: "0.010000",
    unit: "kg_N2O-N/kg_N",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 11",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Poultry Manure - CH4",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "0.110000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.14",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Municipal Solid Waste - Landfill",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "0.550000",
    unit: "ton_CH4/ton_waste",
    source:
      "IPCC 2006 Guidelines, Volume 5, Chapter 3, Waste composition-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Steel Production - Blast Furnace",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "1.850000",
    unit: "ton_CO2/ton_steel",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 4",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Paper/Cardboard - Landfill",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "0.400000",
    unit: "ton_CH4/ton_waste",
    source: "IPCC 2006 Guidelines, Volume 5, Chapter 3, Table 3.1",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Dairy Cattle Manure - N2O",
    gas_type: "N2O",
    tier: "TIER_3",
    value: "0.320000",
    unit: "kg_N2O/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Process-based model",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Municipal Solid Waste - Landfill",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "0.600000",
    unit: "ton_CH4/ton_waste",
    source: "IPCC 2006 Guidelines, Volume 5, Chapter 3, Table 3.1",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Diesel Combustion CH4 - Road Transport",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "0.003200",
    unit: "kg_CH4/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Technology-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Aviation Gasoline Combustion",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "2.310000",
    unit: "kg_CO2/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Country-specific NCV",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Rice Cultivation - Methane",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "1.150000",
    unit: "kg_CH4/ha/season",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 5, Water regime-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Sheep - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "6.200000",
    unit: "kg_CH4/head/year",
    source:
      "IPCC 2006 Guidelines, Volume 4, Chapter 10, Production type-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Jet Kerosene Combustion - Aviation",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "2.540000",
    unit: "kg_CO2/liter",
    source:
      "IPCC 2006 Guidelines, Volume 2, Chapter 3, Fuel specification-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Natural Gas Combustion - Residential",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "1.930000",
    unit: "kg_CO2/m3",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 2",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Municipal Solid Waste - Landfill",
    gas_type: "CH4",
    tier: "TIER_3",
    value: "0.480000",
    unit: "ton_CH4/ton_waste",
    source: "IPCC 2006 Guidelines, Volume 5, Chapter 3, FOD model",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Diesel Combustion - Road Transport",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "2.710000",
    unit: "kg_CO2/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Country-specific NCV",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Diesel Combustion - Road Transport",
    gas_type: "CO2",
    tier: "TIER_3",
    value: "2.650000",
    unit: "kg_CO2/liter",
    source:
      "IPCC 2006 Guidelines, Volume 2, Chapter 3, Vehicle-specific measurement",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Wood Combustion - Residential",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "0.280000",
    unit: "kg_CH4/ton",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 2, Appliance-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Swine Manure - CH4",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "7.000000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.14",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Garden/Park Waste - Landfill",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "0.180000",
    unit: "ton_CH4/ton_waste",
    source: "IPCC 2006 Guidelines, Volume 5, Chapter 3, Moisture-adjusted",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "SF6 - Electrical Equipment",
    gas_type: "SF6",
    tier: "TIER_2",
    value: "0.042000",
    unit: "kg_SF6/equipment/year",
    source:
      "IPCC 2006 Guidelines, Volume 3, Chapter 8, Equipment type-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Diesel Combustion - Road Transport",
    gas_type: "CO2",
    tier: "TIER_3",
    value: "2.650000",
    unit: "kg_CO2/liter",
    source:
      "IPCC 2006 Guidelines, Volume 2, Chapter 3, Vehicle-specific measurement",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Garden/Park Waste - Landfill",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "0.200000",
    unit: "ton_CH4/ton_waste",
    source: "IPCC 2006 Guidelines, Volume 5, Chapter 3, Table 3.1",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "LPG Combustion - Road Transport",
    gas_type: "CO2",
    tier: "TIER_2",
    value: "1.690000",
    unit: "kg_CO2/liter",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 3, Country-specific",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Buffalo - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_2",
    value: "62.000000",
    unit: "kg_CH4/head/year",
    source:
      "IPCC 2006 Guidelines, Volume 4, Chapter 10, Regional characteristics",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Cement Production - Process Emissions",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "0.520000",
    unit: "ton_CO2/ton_clinker",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 2, Equation 2.1",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Coal Combustion - Power Generation",
    gas_type: "CO2",
    tier: "TIER_1",
    value: "2.450000",
    unit: "kg_CO2/kg",
    source: "IPCC 2006 Guidelines, Volume 2, Chapter 2",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Dairy Cattle Manure - N2O",
    gas_type: "N2O",
    tier: "TIER_1",
    value: "0.440000",
    unit: "kg_N2O/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.21",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Dairy Cattle - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_3",
    value: "82.000000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Feed-based model",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Goats - Enteric Fermentation",
    gas_type: "CH4",
    tier: "TIER_1",
    value: "5.000000",
    unit: "kg_CH4/head/year",
    source: "IPCC 2006 Guidelines, Volume 4, Chapter 10, Table 10.10",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
  {
    name: "Steel Production - Blast Furnace",
    gas_type: "CO2",
    tier: "TIER_3",
    value: "1.780000",
    unit: "ton_CO2/ton_steel",
    source: "IPCC 2006 Guidelines, Volume 3, Chapter 4, Mass balance approach",
    applicable_categories: null,
    fuel_type: null,
    activity_type: null,
    heating_value: null,
    heating_value_unit: null,
  },
];
