const fertilizerA = {
  ammoniumNitrate: {
    keterangan: "Ammonium Nitrate",
    satuan: "kg N/ha/yr",
    type: "number",
    disabled: false,
    placeholder: "",
  },
  urea: {
    keterangan: "Urea",
    satuan: "kg N/ha/yr",
    type: "number",
    disabled: false,
    placeholder: "",
  },
  appliedManure: {
    keterangan: "Applied quantity of liquid and solid manure",
    satuan: "kg N/ha/yr",
    type: "number",
    disabled: false,
    placeholder: "",
  },
  nContentCropResidue: {
    keterangan: "N-Content crop residue",
    satuan: "kg N/ha/yr",
    type: "number",
    disabled: false,
    placeholder: "",
  },
  totalNSyntheticFertilizer: {
    keterangan: "Total N amount from synthetic fertilizer",
    satuan: "kg N/ha/yr",
    type: "number",
    disabled: true,
    placeholder: "",
  },
  emissionFactorAmmoniumNitrate: {
    keterangan: "Emission factor Ammonium nitrate",
    satuan: "kgCO2eq/kg N",
    type: "number",
    disabled: false,
    placeholder: "",
  },
  emissionFactorUrea: {
    keterangan: "Emission factor Urea",
    satuan: "kgCO2eq/kg N",
    type: "number",
    disabled: false,
    placeholder: "",
  },
  emissionFactorDirectN2O: {
    keterangan: "Emission factor direct N2O emissions",
    satuan: "kgN2O-N/kg N",
    type: "number",
    disabled: false,
    placeholder: "",
  },
  fractionNVolatilizedSynthetic: {
    keterangan: "Fraction of Nsynt that volatiles as NH3, NOx",
    satuan: "kgN/kg N",
    type: "number",
    disabled: false,
    placeholder: "",
  },
  fractionNVolatilizedOrganic: {
    keterangan: "Fraction of Norg that volatiles as NH3,NOx",
    satuan: "kgN/kg N",
    type: "number",
    disabled: false,
    placeholder: "",
  },
  emissionFactorAtmosphericDeposition: {
    keterangan: "Emission factor atmospheric deposition",
    satuan: "kgN20-N/kg N",
    type: "number",
    disabled: false,
    placeholder: "",
  },
  fractionNLostRunoff: {
    keterangan: "Fraction of mineralized N, lost via runoff/leaching",
    satuan: "kgN/kg N",
    type: "number",
    disabled: false,
    placeholder: "",
  },
  emissionFactorLeachingRunoff: {
    keterangan: "Emission factor leaching/runoff",
    satuan: "kgN20-N/kg N",
    type: "number",
    disabled: false,
    placeholder: "",
  },
};

export default fertilizerA;
