const landUseChangeB = {
  socstReference: {
    keterangan: "SOCST",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
    labelColor: "text-black",
    bold: false,
  },
  fluReference: {
    keterangan: "FLU",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
    labelColor: "text-black",
    bold: false,
  },
  fmgReference: {
    keterangan: "FMG",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
    labelColor: "text-black",
    bold: false,
  },
  fiReference: {
    keterangan: "FI",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
    labelColor: "text-black",
    bold: false,
  },
  cvegReference: {
    keterangan: "Cveg",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
    labelColor: "text-black",
    bold: false,
  },
  soilOrganicCarbonActual: {
    keterangan: "Soil organic carbon actual agricultural practices",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: true,
    labelColor: "text-black",
    bold: false,
  },
  soilOrganicCarbonReference: {
    keterangan: "Soil organic carbon reference agricultural practices",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: true,
    labelColor: "text-black",
    bold: false,
  },
  accumulatedSoilCarbon: {
    keterangan: "Accumulated soil carbon",
    satuan: "ton CO₂eq/ha/yr",
    type: "number",
    placeholder: "",
    disabled: true,
    labelColor: "text-black",
    bold: false,
  },
  lucCarbonEmissionsPerKgCorn: {
    keterangan: "LUC Carbon emissions per kg corn released in the atmosphere",
    satuan: "kg CO₂eq/kg corn",
    type: "number",
    placeholder: "",
    disabled: true,
    labelColor: "text-black",
    bold: false,
  },
  totalLUCCO2EmissionsHaYr: {
    keterangan: "Total LUC carbon emissions released to the atmosphere",
    satuan: "kg CO₂eq/ha/yr",
    type: "number",
    placeholder: "",
    disabled: true,
    labelColor: "text-black",
    bold: true,
  },
  totalLUCCO2EmissionsTDryCorn: {
    keterangan: "",
    satuan: "kg CO₂eq/t dry corn",
    type: "number",
    placeholder: "",
    disabled: true,
    labelColor: "text-black",
    bold: true,
  },
};

export default landUseChangeB;
