const landUseA = {
  actualLandUse: {
    keterangan: "Actual land use",
    satuan: "t/ha/yr",
    type: "text",
    placeholder: "Input Actual land use",
    disabled: false,
  },
  climateRegionActual: {
    keterangan: "Climate region",
    satuan: "t/ha/yr",
    type: "text",
    placeholder: "Input Climate region",
    disabled: false,
  },
  soilTypeActual: {
    keterangan: "Soil type",
    satuan: "t/ha/yr",
    type: "text",
    placeholder: "Input Soil type",
    disabled: false,
  },
  currentSoilManagementActual: {
    keterangan: "Current soil management",
    satuan: "t/ha/yr",
    type: "text",
    placeholder: "Input Current soil management",
    disabled: false,
  },
  currentInputToSoilActual: {
    keterangan: "Current input to soil",
    satuan: "t/ha/yr",
    type: "text",
    placeholder: "Input Current input to soil",
    disabled: false,
  },
  actualCarbonStockSoil: {
    keterangan: "Actual carbon stock in soil",
    satuan: "t/ha/yr",
    type: "number",
    placeholder: "",
    disabled: false,
  },
  socstActual: {
    keterangan: "SOCST",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
  },
  fluActual: {
    keterangan: "FLU",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
  },
  fmgActual: {
    keterangan: "FMG",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
  },
  fiActual: {
    keterangan: "FI",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
  },
  cvegActual: {
    keterangan: "Cveg",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
  },
};

export default landUseA;
