const landUseB = {
  referenceLandUse: {
    keterangan: "Reference land use",
    satuan: "t/ha/yr",
    type: "text",
    placeholder: "Input Reference land use",
    disabled: false,
    labelColor: "text-black",
    bold: false,
  },
  climateRegionReference: {
    keterangan: "Climate region",
    satuan: "t/ha/yr",
    type: "text",
    placeholder: "Input Climate region",
    disabled: false,
    labelColor: "text-black",
    bold: false,
  },
  soilTypeReference: {
    keterangan: "Soil type",
    satuan: "t/ha/yr",
    type: "text",
    placeholder: "Input Soil type",
    disabled: false,
    labelColor: "text-black",
    bold: false,
  },
  currentSoilManagementReference: {
    keterangan: "Current soil management",
    satuan: "t/ha/yr",
    type: "text",
    placeholder: "Input Current soil management",
    disabled: false,
    labelColor: "text-black",
    bold: false,
  },
  currentInputToSoilReference: {
    keterangan: "Current input to soil",
    satuan: "t/ha/yr",
    type: "text",
    placeholder: "Input Current input to soil",
    disabled: false,
    labelColor: "text-black",
    bold: false,
  },
  actualCarbonStockSoilReference: {
    keterangan: "Actual carbon stock in soil",
    satuan: "t/ha/yr",
    type: "number",
    placeholder: "",
    disabled: false,
    labelColor: "text-black",
    bold: false,
  },
  socstReference: {
    keterangan: "SOCST",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
    labelColor: "text-black",
    bold: false,
  },
  fluReference: {
    keterangan: "FLU",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
    labelColor: "text-black",
    bold: false,
  },
  fmgReference: {
    keterangan: "FMG",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
    labelColor: "text-black",
    bold: false,
  },
  fiReference: {
    keterangan: "FI",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
    labelColor: "text-black",
    bold: false,
  },
  cvegReference: {
    keterangan: "Cveg",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
    labelColor: "text-black",
    bold: false,
  },
  soilOrganicCarbonActual: {
    keterangan: "Soil organic carbon actual agricultural practices",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
    labelColor: "text-black",
    bold: false,
  },
  soilOrganicCarbonReference: {
    keterangan: "Soil organic carbon reference agricultural practices",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: true,
    labelColor: "text-black",
    bold: false,
  },
  accumulatedSoilCarbon: {
    keterangan: "Accumulated soil carbon",
    satuan: "ton CO₂eq/ha/yr",
    type: "number",
    placeholder: "",
    disabled: true,
    labelColor: "text-black",
    bold: false,
  },
  lucCarbonEmissionsPerKgCorn: {
    keterangan: "LUC Carbon emissions per kg corn released in the atmosphere",
    satuan: "kg CO₂eq/kg corn",
    type: "number",
    placeholder: "",
    disabled: true,
    labelColor: "text-black",
    bold: false,
  },
  totalLUCCO2EmissionsHaYr: {
    keterangan: "Total LUC carbon emissions released to the atmosphere",
    satuan: "kg CO₂eq/ha/yr",
    type: "number",
    placeholder: "",
    disabled: true,
    labelColor: "text-black",
    bold: true,
  },
  totalLUCCO2EmissionsTDryCorn: {
    keterangan: "",
    satuan: "kg CO₂eq/t dry corn",
    type: "number",
    placeholder: "",
    disabled: true,
    labelColor: "text-black",
    bold: true,
  },
};

export default landUseB;
