const landUse = {
  actualLandUse: {
    keterangan: "Actual land use",
    satuan: "t/ha/yr",
    type: "text",
    placeholder: "Input Actual land use",
    disabled: false,
  },
  climateRegionActual: {
    keterangan: "Climate region",
    satuan: "t/ha/yr",
    type: "text",
    placeholder: "Input Climate region",
    disabled: false,
  },
  soilTypeActual: {
    keterangan: "Soil type",
    satuan: "t/ha/yr",
    type: "text",
    placeholder: "Input Soil type",
    disabled: false,
  },
  currentSoilManagementActual: {
    keterangan: "Current soil management",
    satuan: "t/ha/yr",
    type: "text",
    placeholder: "Input Current soil management",
    disabled: false,
  },
  currentInputToSoilActual: {
    keterangan: "Current input to soil",
    satuan: "t/ha/yr",
    type: "text",
    placeholder: "Input Current input to soil",
    disabled: false,
  },
  actualCarbonStockSoil: {
    keterangan: "Actual carbon stock in soil",
    satuan: "t/ha/yr",
    type: "number",
    placeholder: "",
    disabled: false,
  },
  socstActual: {
    keterangan: "SOCST",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
  },
  fluActual: {
    keterangan: "FLU",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
  },
  fmgActual: {
    keterangan: "FMG",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
  },
  fiActual: {
    keterangan: "FI",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
  },
  cvegActual: {
    keterangan: "Cveg",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
  },
  referenceLandUse: {
    keterangan: "Reference land use",
    satuan: "t/ha/yr",
    type: "text",
    placeholder: "Input Reference land use",
    disabled: false,
  },
  climateRegionReference: {
    keterangan: "Climate region",
    satuan: "t/ha/yr",
    type: "text",
    placeholder: "Input Climate region",
    disabled: false,
  },
  soilTypeReference: {
    keterangan: "Soil type",
    satuan: "t/ha/yr",
    type: "text",
    placeholder: "Input Soil type",
    disabled: false,
  },
  currentSoilManagementReference: {
    keterangan: "Current soil management",
    satuan: "t/ha/yr",
    type: "text",
    placeholder: "Input Current soil management",
    disabled: false,
  },
  currentInputToSoilReference: {
    keterangan: "Current input to soil",
    satuan: "t/ha/yr",
    type: "text",
    placeholder: "Input Current input to soil",
    disabled: false,
  },
  actualCarbonStockSoilReference: {
    keterangan: "Actual carbon stock in soil",
    satuan: "t/ha/yr",
    type: "number",
    placeholder: "",
    disabled: false,
  },
  socstReference: {
    keterangan: "SOCST",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
  },
  fluReference: {
    keterangan: "FLU",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
  },
  fmgReference: {
    keterangan: "FMG",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
  },
  fiReference: {
    keterangan: "FI",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
  },
  cvegReference: {
    keterangan: "Cveg",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
  },
  soilOrganicCarbonActual: {
    keterangan: "Soil organic carbon actual agricultural practices",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: false,
  },
  soilOrganicCarbonReference: {
    keterangan: "Soil organic carbon reference agricultural practices",
    satuan: "ton C /ha",
    type: "number",
    placeholder: "",
    disabled: true,
  },
  accumulatedSoilCarbon: {
    keterangan: "Accumulated soil carbon",
    satuan: "ton CO2eq/ha/yr",
    type: "number",
    placeholder: "",
    disabled: true,
  },
  lucCarbonEmissionsPerKgCorn: {
    keterangan: "LUC Carbon emissions per kg corn released in the atmosphere",
    satuan: "kg CO2eq/kg corn",
    type: "number",
    placeholder: "",
    disabled: true,
  },
  totalLUCCO2EmissionsHaYr: {
    keterangan: "Total LUC carbon emissions released to the atmosphere",
    satuan: "kg CO2eq/ha/yr",
    type: "number",
    placeholder: "",
    disabled: true,
  },
  totalLUCCO2EmissionsTDryCorn: {
    keterangan: "Total LUC CO2 emissions per ton dry corn",
    satuan: "kg CO2eq/t dry corn",
    type: "number",
    placeholder: "",
    disabled: true,
  },
};

export default landUse;
