const allofactor = {
  allofactorElectricity: {
    keterangan: "Electricity from grid",
    satuan: "kg CO₂eq/Year",
    type: "number",
    disabled: true,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  allofactorSteamNaturalGas: {
    keterangan: "Steam consumption natural gas",
    satuan: "kg CO₂eq/Year",
    type: "number",
    disabled: true,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  allofactorYeast: {
    keterangan: "Yeast for fermentation",
    satuan: "kg CO₂eq/Year",
    type: "number",
    disabled: true,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  allofactorFreshWater: {
    keterangan: "Fresh water",
    satuan: "kg CO₂eq/Year",
    type: "number",
    disabled: true,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  allofactorEnzymes: {
    keterangan: "Process-specific enzymes",
    satuan: "kg CO₂eq/Year",
    type: "number",
    disabled: true,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  allofactorSulfuricAcid: {
    keterangan: "Sulfuric Acid",
    satuan: "kg CO₂eq/Year",
    type: "number",
    disabled: true,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  allofactorSodiumHydroxide: {
    keterangan: "Sodium Hydroxide",
    satuan: "kg CO₂eq/Year",
    type: "number",
    disabled: true,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  allofactorUrea: {
    keterangan: "Urea",
    satuan: "kg CO₂eq/Year",
    type: "number",
    disabled: true,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  allofactorTotal: {
    keterangan: "Process-specific emissions",
    satuan: "kg CO₂eq/Year",
    type: "number",
    disabled: true,
    placeholder: "",
    labelColor: "text-black",
    bold: true,
  },
  allofactorPerTonBioethanol: {
    keterangan: "",
    satuan: "kg CO₂eq/mt Bioethanol",
    type: "number",
    disabled: true,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
};

export default allofactor;
