const coProduct = {
  cornOil: {
    keterangan: "Corn oil",
    satuan: "mt/Year",
    type: "number",
    disabled: false,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  cornOilMoisture: {
    keterangan: "Moisture content of corn oil",
    satuan: "%",
    type: "number",
    disabled: false,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  ddgs: {
    keterangan: "Dried Distillers Grains with Solubles (DDGS)",
    satuan: "mt/Year",
    type: "number",
    disabled: false,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  ddgsMoisture: {
    keterangan: "Moisture content of DDGS",
    satuan: "%",
    type: "number",
    disabled: false,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  wdg: {
    keterangan: "Wet Distillers Grains (WDG)",
    satuan: "mt/Year",
    type: "number",
    disabled: false,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  wdgMoisture: {
    keterangan: "Moisture content of WDG",
    satuan: "%",
    type: "number",
    disabled: false,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  syrup: {
    keterangan: "Soluble Distillers Grains (Syrup)",
    satuan: "mt/Year",
    type: "number",
    disabled: false,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  syrupMoisture: {
    keterangan: "Moisture content of Syrup",
    satuan: "%",
    type: "number",
    disabled: false,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
};

export default coProduct;
