const emissionFactor = {
  emissionFactorElectricity: {
    keterangan: "Electricity from grid",
    satuan: "kg CO₂eq/kWh",
    type: "number",
    disabled: false,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  emissionFactorNaturalGas: {
    keterangan: "Natural Gas",
    satuan: "kg CO₂eq/MJ",
    type: "number",
    disabled: false,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  emissionFactorYeast: {
    keterangan: "Yeast for fermentation",
    satuan: "kg CO₂eq/kg",
    type: "number",
    disabled: false,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  emissionFactorFreshWater: {
    keterangan: "Fresh water",
    satuan: "kg CO₂eq/kg",
    type: "number",
    disabled: false,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  emissionFactorAlphaAmylase: {
    keterangan: "Alpha Amylase Enzyme",
    satuan: "kg CO₂eq/kg",
    type: "number",
    disabled: false,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  emissionFactorGlucoAmylase: {
    keterangan: "Gluco Amylase Enzyme",
    satuan: "kg CO₂eq/kg",
    type: "number",
    disabled: false,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  emissionFactorSulfuricAcid: {
    keterangan: "Sulfuric Acid",
    satuan: "kg CO₂eq/kg",
    type: "number",
    disabled: false,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  emissionFactorSodiumHydroxide: {
    keterangan: "Sodium Hydroxide",
    satuan: "kg CO₂eq/kg",
    type: "number",
    disabled: false,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  emissionFactoorUrea: {
    keterangan: "Urea",
    satuan: "kg CO₂eq/kg",
    type: "number",
    disabled: false,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
};

export default emissionFactor;
