const processSpecificInputs = {
  yeastFermentation: {
    keterangan: "Yeast for fermentation",
    satuan: "kg/Year",
    type: "number",
    disabled: false,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  freshWater: {
    keterangan: "Amount of fresh water deployed",
    satuan: "mt/Year",
    type: "number",
    disabled: false,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  alphaAmylase: {
    keterangan: "Alpha Amylase Enzyme",
    satuan: "kg/Year",
    type: "number",
    disabled: false,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  glucoAmylase: {
    keterangan: "Gluco Amylase Enzyme",
    satuan: "kg/Year",
    type: "number",
    disabled: false,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  sulfuricAcid: {
    keterangan: "Sulfuric Acid",
    satuan: "kg/Year",
    type: "number",
    disabled: false,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  sodiumHydroxide: {
    keterangan: "Sodium Hydroxide",
    satuan: "kg/Year",
    type: "number",
    disabled: false,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
  urea: {
    keterangan: "Urea",
    satuan: "kg/Year",
    type: "number",
    disabled: false,
    placeholder: "",
    labelColor: "text-black",
    bold: false,
  },
};

export default processSpecificInputs;
